import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline-variant": "#c3c6d7",
        "surface-dim": "#d2d9f4",
        "tertiary": "#9a3e00",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "inverse-surface": "#283044",
        "on-tertiary-fixed-variant": "#7a3000",
        "primary-fixed": "#dae2ff",
        "surface-container-high": "#e2e7ff",
        "inverse-on-surface": "#eef0ff",
        "secondary-container": "#6cf8bb",
        "inverse-primary": "#b2c5ff",
        "secondary-fixed": "#6ffbbe",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#c25000",
        "on-secondary-fixed": "#002113",
        "surface": "#faf8ff",
        "surface-variant": "#dae2fd",
        "on-error": "#ffffff",
        "primary-container": "#2c6bed",
        "surface-tint": "#0055d4",
        "on-secondary": "#ffffff",
        "background": "#faf8ff",
        "on-primary-fixed": "#001848",
        "on-surface-variant": "#424654",
        "on-surface": "#131b2e",
        "surface-container": "#eaedff",
        "tertiary-fixed-dim": "#ffb693",
        "on-background": "#131b2e",
        "on-primary-container": "#fbf9ff",
        "surface-bright": "#faf8ff",
        "outline": "#737686",
        "surface-container-highest": "#dae2fd",
        "on-primary": "#ffffff",
        "on-secondary-container": "#00714d",
        "secondary-fixed-dim": "#4edea3",
        "primary": "#0052cd",
        "tertiary-fixed": "#ffdbcc",
        "on-tertiary-fixed": "#351000",
        "primary-fixed-dim": "#b2c5ff",
        "secondary": "#006c49",
        "on-secondary-fixed-variant": "#005236",
        "on-primary-fixed-variant": "#003fa3",
        "surface-container-low": "#f2f3ff",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#fff9f8"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-sm": "0.5rem",
        "chat-max-width": "54rem",
        "sidebar-width": "22rem",
        "space-xs": "0.25rem",
        "space-md": "0.75rem",
        "space-2xs": "0.125rem",
        "gutter-mobile": "0.75rem",
        "space-2xl": "2rem",
        "gutter-desktop": "1.5rem",
        "space-base": "1rem",
        "space-3xl": "3rem",
        "space-lg": "1.25rem",
        "space-xl": "1.5rem"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "timestamp": ["Inter", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["1.0625rem", { lineHeight: "1.5rem", letterSpacing: "-0.005em", fontWeight: "400" }],
        "label-sm": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.01em", fontWeight: "500" }],
        "timestamp": ["0.6875rem", { lineHeight: "0.875rem", letterSpacing: "0.02em", fontWeight: "400" }],
        "code-sm": ["0.8125rem", { lineHeight: "1.125rem", letterSpacing: "0.05em", fontWeight: "500" }],
        "headline-lg-mobile": ["1.5rem", { lineHeight: "2rem", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-sm": ["1rem", { lineHeight: "1.5rem", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-md": ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "0.005em", fontWeight: "500" }],
        "display-lg": ["2.25rem", { lineHeight: "2.75rem", letterSpacing: "-0.025em", fontWeight: "700" }],
        "body-md": ["0.9375rem", { lineHeight: "1.375rem", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["0.8125rem", { lineHeight: "1.125rem", letterSpacing: "0.005em", fontWeight: "400" }],
        "headline-md": ["1.25rem", { lineHeight: "1.75rem", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-lg": ["1.75rem", { lineHeight: "2.25rem", letterSpacing: "-0.02em", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
};
export default config;
