name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare Directory Permissions
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo mkdir -p /mnt/storage/iex-dashboard-old
            sudo chown -R ubuntu:ubuntu /mnt/storage/iex-dashboard-old

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/mnt/storage/iex-dashboard-old"
          strip_components: 0

      - name: Start Docker Containers
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /mnt/storage/iex-dashboard-old
            # Ensure the deployment doesn't conflict by building and starting detached
            sudo docker compose up -d --build
            # Restart Nginx to clear Docker internal DNS cache (prevents 502 Bad Gateway)
            sudo docker compose restart nginx
